### ISSUE TITLE
C implementation doesn't restore terminal colors currently

### ISSUE THREAD

**Issue by Kusoneko** [swindlesmccoop/terminal-flirt#1]
What the title says. I can't seem to be able to upload a screenshot to github right now for some unknown reason, but I tested it with say lsblk, mv, rm or cp (for those last 3 I have them aliased with the -iv options which means it always tells me what it did and asks before doing some things like overwriting or deleting files), etc, so long as the command used doesn't itself change the terminal colors as well and so long as it produces an output. Considering most people would normally configure their shell prompt, at least on bash or zsh, to use specific colors, the issue doesn't persist between commands, unless for some reason someone has the most vanilla PS1 possible with literally no color modifications to it.

It should be a relatively trivial fix to do, I'm gonna look into doing so and making a PR right after posting this issue, unless I get beaten to it.

Edit: PR is up.

**Comment by swindlesmccoop** [comment]
Unsure how I even overlooked this, since I'm pretty sure it is part of the sh implementation.
